---
- name: Reset UFW
  ufw:
    state: reset

- name: Add UFW rule to allow incoming SSH
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Add UFW rule to allow incoming HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Add UFW rule to allow incoming HTTPS
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow all outgoing default
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Disallow all incoming except the allowed services
  community.general.ufw:
    direction: incoming
    default: deny


- name: Enable UFW
  community.general.ufw:
    state: enabled